-- CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE TOPICOS;
-- CRIAÇÃO DAS TABELAS
CREATE TABLE LOGIN (ID INT AUTO_INCREMENT PRIMARY KEY, USUARIO VARCHAR(100), SENHA VARCHAR(100));
CREATE TABLE JOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, TITULO VARCHAR(200), PRECO FLOAT, IMAGEM LONGBLOB);
CREATE TABLE ACESSORIOS (ID INT AUTO_INCREMENT PRIMARY KEY, NOME VARCHAR(200), PRECO FLOAT, IMAGEM LONGBLOB);
CREATE TABLE CONTATO (ID INT AUTO_INCREMENT PRIMARY KEY,NOME VARCHAR(200), EMAIL VARCHAR(200), MENSAGEM VARCHAR(3000), RESPOSTA VARCHAR(3000));
CREATE TABLE COMPRA (ID INT AUTO_INCREMENT PRIMARY KEY, PRODUTO VARCHAR(200), PRECO FLOAT, QUANTIDADE INT, PLATAFORMA VARCHAR(50));
CREATE TABLE NOTICIAS (ID INT AUTO_INCREMENT PRIMARY KEY, TITULO VARCHAR(1000), DESCRICAO VARCHAR(5000), DATA DATE);

SELECT * FROM LOGIN



