-- CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE TOPICOS

-- CRIAÇÃO DAS TABELAS
CREATE TABLE LOGIN (ID INT AUTO_INCREMENT PRIMARY KEY, USUARIO VARCHAR(100), SENHA VARCHAR(100))

SELECT * FROM LOGIN

INSERT INTO LOGIN (USUARIO, SENHA) VALUES (MD5('admin'), MD5('admin'))

DELETE FROM LOGIN WHERE ID < 9389893